name = "Einops"
uuid = "e3ce28c8-8bfb-4704-8add-e3e7f14b55c9"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"

[compat]
ChainRulesCore = "1.7"
EllipsisNotation = "1"
Statistics = "1"
Zygote = "0.6"
julia = "1.6"

[extras]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Statistics", "Zygote"]
